theme="tokyonight"

[editor]
line-number="relative"
bufferline="multiple"
mouse=false

[editor.cursor-shape]
insert="bar"

[keys.normal]
esc=["collapse_selection","keep_primary_selection"]
C-p="file_picker"
tab="goto_next_buffer"
S-tab="goto_previous_buffer"
[keys.normal.space]
ret=":q"

[keys.normal.space.l]
f=":format"
